name: Run tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - dev
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"  # change to match your project

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev] 

      - name: Run tests with pytest
        run: |
          pytest --cov=causal_falsify --cov-fail-under=80 tests/
